# Generated by Django 4.2.6 on 2023-12-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
