# Generated by Django 4.2.6 on 2023-12-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_rename_img_login_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
