# Generated by Django 4.2.6 on 2023-12-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in', models.IntegerField()),
                ('id_out', models.IntegerField()),
                ('mes', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('statuts', models.IntegerField()),
            ],
        ),
    ]
