# Generated by Django 4.2.6 on 2023-12-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='Chat_Box',
        ),
    ]
