# Generated by Django 4.2.6 on 2023-12-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_chat_box_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='detail_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_group', models.IntegerField()),
                ('id_user', models.IntegerField()),
                ('mes', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='file')),
            ],
        ),
    ]
