# Generated by Django 4.2.6 on 2023-12-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0005_chat_group_detail_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('id_group', models.IntegerField()),
                ('mes', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='file')),
            ],
        ),
        migrations.RemoveField(
            model_name='detail_group',
            name='file',
        ),
        migrations.RemoveField(
            model_name='detail_group',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='detail_group',
            name='status',
        ),
        migrations.RemoveField(
            model_name='detail_group',
            name='time',
        ),
        migrations.AddField(
            model_name='chat_group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
