# Generated by Django 4.2.6 on 2023-12-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0008_alter_group_chat_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_chat',
            name='url_file',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
