# Generated by Django 4.2.6 on 2023-12-19 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0009_group_chat_url_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_chat',
            name='file',
        ),
    ]
