# Generated by Django 4.2.6 on 2023-12-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0010_remove_group_chat_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_box',
            name='file',
        ),
        migrations.RemoveField(
            model_name='chat_group',
            name='image',
        ),
        migrations.AddField(
            model_name='chat_box',
            name='url_file',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chat_group',
            name='url_image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
